package com.itheima.domain;

import java.io.Serializable;
import java.util.Date;

public class Member implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_member.id
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_member.nick_name
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_member.password
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_member.gender
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_member.birthday
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_member.email
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_member.state
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_member.telephone
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_member.address
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_member.register_date
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tr_member
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_member.id
     *
     * @return the value of tr_member.id
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_member.id
     *
     * @param id the value for tr_member.id
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_member.nick_name
     *
     * @return the value of tr_member.nick_name
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_member.nick_name
     *
     * @param nickName the value for tr_member.nick_name
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_member.password
     *
     * @return the value of tr_member.password
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_member.password
     *
     * @param password the value for tr_member.password
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_member.gender
     *
     * @return the value of tr_member.gender
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_member.gender
     *
     * @param gender the value for tr_member.gender
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_member.birthday
     *
     * @return the value of tr_member.birthday
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_member.birthday
     *
     * @param birthday the value for tr_member.birthday
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_member.email
     *
     * @return the value of tr_member.email
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_member.email
     *
     * @param email the value for tr_member.email
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_member.state
     *
     * @return the value of tr_member.state
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_member.state
     *
     * @param state the value for tr_member.state
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_member.telephone
     *
     * @return the value of tr_member.telephone
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_member.telephone
     *
     * @param telephone the value for tr_member.telephone
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_member.address
     *
     * @return the value of tr_member.address
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_member.address
     *
     * @param address the value for tr_member.address
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_member.register_date
     *
     * @return the value of tr_member.register_date
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_member.register_date
     *
     * @param registerDate the value for tr_member.register_date
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_member
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Member other = (Member) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNickName() == null ? other.getNickName() == null : this.getNickName().equals(other.getNickName()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getRegisterDate() == null ? other.getRegisterDate() == null : this.getRegisterDate().equals(other.getRegisterDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_member
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNickName() == null) ? 0 : getNickName().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getRegisterDate() == null) ? 0 : getRegisterDate().hashCode());
        return result;
    }
}