package com.itheima.mapper;

import com.itheima.domain.Member;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_member
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @Delete({
        "delete from tr_member",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_member
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @Insert({
        "insert into tr_member (id, nick_name, ",
        "password, gender, ",
        "birthday, email, ",
        "state, telephone, ",
        "address, register_date)",
        "values (#{id,jdbcType=VARCHAR}, #{nickName,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{gender,jdbcType=VARCHAR}, ",
        "#{birthday,jdbcType=TIMESTAMP}, #{email,jdbcType=VARCHAR}, ",
        "#{state,jdbcType=VARCHAR}, #{telephone,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{registerDate,jdbcType=TIMESTAMP})"
    })
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_member
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @InsertProvider(type=MemberSqlProvider.class, method="insertSelective")
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_member
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @Select({
        "select",
        "id, nick_name, password, gender, birthday, email, state, telephone, address, ",
        "register_date",
        "from tr_member",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="nick_name", property="nickName", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
        @Result(column="birthday", property="birthday", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.VARCHAR),
        @Result(column="telephone", property="telephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="register_date", property="registerDate", jdbcType=JdbcType.TIMESTAMP)
    })
    Member selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_member
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @UpdateProvider(type=MemberSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_member
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @Update({
        "update tr_member",
        "set nick_name = #{nickName,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=VARCHAR},",
          "birthday = #{birthday,jdbcType=TIMESTAMP},",
          "email = #{email,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=VARCHAR},",
          "telephone = #{telephone,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "register_date = #{registerDate,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Member record);
}