package com.itheima.mapper;

import com.itheima.domain.QuestionItem;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface QuestionItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @Delete({
        "delete from question_item",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @Insert({
        "insert into question_item (id, question_id, ",
        "content)",
        "values (#{id,jdbcType=INTEGER}, #{questionId,jdbcType=INTEGER}, ",
        "#{content,jdbcType=VARCHAR})"
    })
    int insert(QuestionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @InsertProvider(type=QuestionItemSqlProvider.class, method="insertSelective")
    int insertSelective(QuestionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @Select({
        "select",
        "id, question_id, content",
        "from question_item",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="question_id", property="questionId", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR)
    })
    QuestionItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @UpdateProvider(type=QuestionItemSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(QuestionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbg.generated Thu Dec 09 14:38:49 CST 2021
     */
    @Update({
        "update question_item",
        "set question_id = #{questionId,jdbcType=INTEGER},",
          "content = #{content,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(QuestionItem record);
}